### PR TITLE
chore: add Prettier for consistent formatting

### PR DESCRIPTION
**Pull request by willynganga**

### CODE REVIEW

**Review by robertnd — CHANGES_REQUESTED** [review]
I prefer Typescript & JS without semi-colons. I use other languages that don't have it,  dealing with it now is going to drive me mad.

**Comment by kbuika** [comment]
LGTM🚀

**Review by kbuika — APPROVED** [review]
LGTM!

**Review by robertnd — APPROVED** [review]
LGTM

**Pull request merged**
